### ISSUE TITLE
YAML data terminated with ... throws error

### ISSUE THREAD

**Issue by s6mike** [api7/lua-tinyyaml#22]
e.g.

``` yaml

---
'Map 2: All swans are white.':
  r2:
    Every swan I’ve ever seen is white.: []
    These swans are representative of all swans.: []
  o1:
    Not all swans are white.: []
...

```

``` shell
lua: ...t_projects/argmap/lua_modules/share/lua/5.3/tinyyaml.lua:707: failed to classify line: ...

stack traceback:
        [C]: in function 'error'
        ...t_projects/argmap/lua_modules/share/lua/5.3/tinyyaml.lua:707: in upvalue 'parsemap'
        ...t_projects/argmap/lua_modules/share/lua/5.3/tinyyaml.lua:793: in upvalue 'parsedocuments'
        ...t_projects/argmap/lua_modules/share/lua/5.3/tinyyaml.lua:818: in function 'tinyyaml.parse'
        /opt/miniconda3/envs/argmap/bin/argmap2mup:594: in function 'main'
        /opt/miniconda3/envs/argmap/bin/argmap2mup:642: in main chunk
        [C]: in ?
```

Removing the final ... in the yaml data fixes the error.
